---
sudo: false
cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal
    - $HOME/.ghc
addons:
  apt:
    packages:
      - libgmp3-dev
      - xz-utils
      - liblzma-dev
      - bzip2
matrix:
  include:

    # Linux
    - env: TARGET=x86_64-unknown-linux
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.4.1
            - cabal-install-head
      language: python

    # OS X
    - env: TARGET=x86_64-apple-darwin
      os: osx
      language: default

  allow_failures:
    - env: TARGET=x86_64-apple-darwin

before_install:
  - rm -rf ~/.cabal
  - rm -rf ~/.stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install lzlib
      brew install xz
      brew install bzip2
      curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  - stack --no-terminal build --haddock --no-haddock-deps --test --bench --no-run-tests --no-run-benchmarks
  - curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .
  - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
  - |
    if [ `uname` = "Darwin" ]
    then
      export BINPATH="$(find . -name atspkg -perm 755 | tail -n1)"
    else
      export BINPATH="$(find -name atspkg -executable | tail -n4 | head -n1)"
    fi
  - echo $BINPATH
  - |
    if [ `uname` = "Darwin" ]
    then
      mv $BINPATH atspkg-$TARGET
    else
      mv $BINPATH/atspkg atspkg-$TARGET
    fi
  - |
    if [ `uname` = "Darwin" ]
    then
      export BINPATH="$(find .stack-work -name atsfmt -perm 755 | tail -n1)"
    else
      export BINPATH="$(find -name atsfmt -executable | tail -n1)"
    fi
  - echo $BINPATH
  - mv $BINPATH atsfmt-$TARGET
  - strip atspkg-$TARGET
  - du -h atspkg-$TARGET
  - strip atsfmt-$TARGET

deploy:
  api_key:
    secure: "IZLQxO3HtTM2nqowxVOY3MhRhGZTElXUn0jpyPBkbrxLzk8Ykac15lSAGOs4MYo/GdKof8YYr2fHGChv7/PkF/HYSLFcDrY0UzpCP8QqANWjKbakQmVqU+YTtas3cq/Gk1l2tY9MGDNfMB7jk92Nh6BsA1TxReyziVPCDJv+z4UYZqQGhBxYQlVqHlcxYpS0p5gmXTFC8+io/ArGzC4jHqaZ+LmrzVMiXdDeQnVIOtQHbwWLwPb6mXBA8W5qC/IAgivb+w9aH86GUgML2t16b2/pCHQANigaeDTAseaU2PUv2fJTqexBfrAH34FJ+TQxROi8JpXu2/SVDuironTOPhUSnVd3aYNd64lOB80UmCxIWxYcYVA7olr6Qth1ZfKI0ks64sXJ7XlLDykCPqSTdnuiCEsqlHll+2ZA2uEHKuwRxMht/ZxKnW6a6GidaRp2cImBe7sMBQyiLYzf6+ZJQyy7H5beV9FsiTAyA4oxEGtl+220i0kwz6CV4+WXeoO7yv4TAKVfIEMjvHANV/kWEztuwcs3kIJzXJd1J/TdAneOHOCKGbnqDSDNeY48upwaPCQOnNA+RK4PYiA0YJ5zoq8hamtaMVzciGWMX3rFux9qC4wjgcTafFwyF3MSuF/TitAZI/xAtCOnCsZspuaBXI1nuoLoF61oixvD9xMeyNo="
  file:
    - atspkg-$TARGET
    - atsfmt-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /\d+\.\d+\.\d+\.\d+.*$/
    - master
